
name: Docker Image CI

on:
  push:
    branches: [ chinanews-v4.2.0-b2 ]
  pull_request:
    branches: [ chinanews-v4.2.0-b2 ]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: chinanews/mastodon:v4.2.0b2-chinanews

#      - name: Push to Docker Hub Static Files
#        uses: docker/build-push-action@v2
#        with:
#          push: true
#          tags: chinanews/mastodon:chinanews-st
#          file: Dockerfile_staticfiles
#          build-contexts: |
#            sourceimage=docker-image://chinanews/mastodon:v4.1.2-chinanews
